### ISSUE TITLE
UpdateUser mangler nogle felter

### ISSUE THREAD

**Issue by kimsand123** [FredMar/2.sem-CDIO-1#8]

**Comment by 163312** [comment]
saa tager UpdateUser sig af cpr, initialer og password

**Comment by hjaltebaekgaard** [comment]
UpdateUserController needs to be fleshed out too for it to run the new code

**Comment by 163312** [comment]
UpdateUserController should be updated by now :)

**Comment by hjaltebaekgaard** [comment]
Should work now, please test it before concluding it works.

**Comment by 163312** [comment]
it is tested, and it works

**Comment by FredMar** [comment]
@163312  Can it be closed then?
